@php
$courseItems = [
[
'title' => 'Academic Writing',
'mode' => 'Online',
'level' => 'Advanced',
'price' => 'Rp. 100.000',
'description' => 'Refine your ability to construct complex arguments and professional research papers...',
'image' => 'https://placehold.co/800x500/0A1A24/F8FAFC?text=Academic+Writing',
'href' => route('courses.show'),
],
[
'title' => 'IELTS Breakthrough',
'mode' => 'Offline',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Strategic preparation focused on achieving Band 8+ through intensive practice and expe...',
'image' => 'https://placehold.co/800x500/EAE5DD/1E293B?text=IELTS+Breakthrough',
],
[
'title' => 'Executive',
'mode' => 'Offline',
'level' => 'Advanced',
'price' => 'Rp. 100.000',
'description' => 'Master the nuances of professional English for boardrooms, high-stakes negotiations, and...',
'image' => 'https://placehold.co/800x500/6D7E86/F8FAFC?text=Executive',
],
[
'title' => 'IELTS Breakthrough',
'mode' => 'Offline',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Strategic preparation focused on achieving Band 8+ through intensive practice and expe...',
'image' => 'https://placehold.co/800x500/EAE5DD/1E293B?text=IELTS+Breakthrough',
],
[
'title' => 'Speaking Confidence',
'mode' => 'Offline',
'level' => 'Beginner',
'price' => 'Rp. 100.000',
'description' => 'Break language barriers and gain the courage to speak fluently in any social or business...',
'image' => 'https://placehold.co/800x500/4E6B6D/F8FAFC?text=Speaking+Confidence',
],
[
'title' => 'Grammar Essentials',
'mode' => 'Online',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Deep dive into the structural foundations of English for precise and sophisticated languag...',
'image' => 'https://placehold.co/800x500/F2F2F2/1E293B?text=Grammar+Essentials',
],
[
'title' => 'Public Speaking Pro',
'mode' => 'Online',
'level' => 'Advanced',
'price' => 'Rp. 100.000',
'description' => 'Persuade and inspire. Techniques for impactful presentations, storytelling, and charismatic...',
'image' => 'https://placehold.co/800x500/0E1116/F8FAFC?text=Public+Speaking+Pro',
],
[
'title' => 'Grammar Essentials',
'mode' => 'Online',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Deep dive into the structural foundations of English for precise and sophisticated languag...',
'image' => 'https://placehold.co/800x500/F2F2F2/1E293B?text=Grammar+Essentials',
],
[
'title' => 'Academic Writing',
'mode' => 'Online',
'level' => 'Advanced',
'price' => 'Rp. 100.000',
'description' => 'Refine your ability to construct complex arguments and professional research papers...',
'image' => 'https://placehold.co/800x500/0A1A24/F8FAFC?text=Academic+Writing',
'href' => route('courses.show'),
],
[
'title' => 'IELTS Breakthrough',
'mode' => 'Offline',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Strategic preparation focused on achieving Band 8+ through intensive practice and expe...',
'image' => 'https://placehold.co/800x500/EAE5DD/1E293B?text=IELTS+Breakthrough',
],
[
'title' => 'Executive',
'mode' => 'Offline',
'level' => 'Advanced',
'price' => 'Rp. 100.000',
'description' => 'Master the nuances of professional English for boardrooms, high-stakes negotiations, and...',
'image' => 'https://placehold.co/800x500/6D7E86/F8FAFC?text=Executive',
],
[
'title' => 'IELTS Breakthrough',
'mode' => 'Offline',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Strategic preparation focused on achieving Band 8+ through intensive practice and expe...',
'image' => 'https://placehold.co/800x500/EAE5DD/1E293B?text=IELTS+Breakthrough',
],
[
'title' => 'Speaking Confidence',
'mode' => 'Offline',
'level' => 'Beginner',
'price' => 'Rp. 100.000',
'description' => 'Break language barriers and gain the courage to speak fluently in any social or business...',
'image' => 'https://placehold.co/800x500/4E6B6D/F8FAFC?text=Speaking+Confidence',
],
[
'title' => 'Grammar Essentials',
'mode' => 'Online',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Deep dive into the structural foundations of English for precise and sophisticated languag...',
'image' => 'https://placehold.co/800x500/F2F2F2/1E293B?text=Grammar+Essentials',
],
[
'title' => 'Public Speaking Pro',
'mode' => 'Online',
'level' => 'Advanced',
'price' => 'Rp. 100.000',
'description' => 'Persuade and inspire. Techniques for impactful presentations, storytelling, and charismatic...',
'image' => 'https://placehold.co/800x500/0E1116/F8FAFC?text=Public+Speaking+Pro',
],
[
'title' => 'Grammar Essentials',
'mode' => 'Online',
'level' => 'Intermediate',
'price' => 'Rp. 100.000',
'description' => 'Deep dive into the structural foundations of English for precise and sophisticated languag...',
'image' => 'https://placehold.co/800x500/F2F2F2/1E293B?text=Grammar+Essentials',
],
];
@endphp

<section class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-12 lg:px-8">
        <x-public.course-grid :courses="$courseItems" />
    </div>
</section>